version: 0.2
phases:
  install:
    commands:
    - pip3 install -r requirements.txt -t lambda
    - pip3 install possum
    - possum codepipeline-oracle-sam --template-file template.yaml
      --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
  # - outputSamTemplate.yaml
  - '**/*'

