version: 0.2
phases:
  install:
    commands:
    - pip3 install -r requirements.txt
    - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-oracle-sam
      --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
  # - outputSamTemplate.yaml
  - '**/*'

