version: 0.2
phases:
  install:
    commands:
    - npm install
    - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-oracle-sam
      --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
  - outputSamTemplate.yaml