AWSTemplateFormatVersion: '2010-09-09'
Description: 'oracle-api http api service for oracle

  '
Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME: riiid.oracle.development
    Timeout: 3
Resources:
  NodejsHandler:
    Properties:
      CodeUri: s3://codepipeline-oracle-sam/7b1a19502749c3170c92f438d84fe26c
      Events:
        NodejsTest:
          Properties:
            Method: get
            Path: /nodejs8.10
          Type: Api
      Handler: test_handler.test_handler
      Policies:
      - S3ReadPolicy:
          BucketName: riiid.oracle.development
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PythonHandler:
    Properties:
      CodeUri: s3://codepipeline-oracle-sam/880ec794b55051c3f87770923cdb8d30
      Events:
        PythonTest:
          Properties:
            Method: get
            Path: /python_handler
          Type: Api
      Handler: handler.dev_test_handler
      Policies:
      - S3ReadPolicy:
          BucketName: riiid.oracle.development
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
