AWSTemplateFormatVersion: '2010-09-09'
Description: 'oracle-api http api service for oracle

  '
Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME: riiid.oracle.development
    Timeout: 3
Resources:
  NodejsHandler:
    Properties:
      CodeUri: s3://codepipeline-oracle-sam/4bf9a78f936fb9bc80541c1f9d412b91
      Events:
        S3Matrix:
          Properties:
            Topic: arn:aws:sns:ap-northeast-1:340519826608:MatrixPut
          Type: SNS
      Handler: node_sdk_test_linear_algebra.mainHandler
      Policies:
      - S3ReadPolicy:
          BucketName: riiid.oracle.development
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
