AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  oracle-api
  http api service for oracle

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        BUCKET_NAME: riiid.oracle.development

Resources:
  PythonHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://codepipeline-oracle-sam/possum-1536736855/8763e45e18e1483c80fb99de5d321fe3.zip
      Handler: handler.dev_test_handler
      Runtime: python3.6
      Events:
        PythonTest:
          Type: Api
          Properties:
            Path: /python_handler
            Method: get
      Policies:
      - S3ReadPolicy:
          BucketName: riiid.oracle.development
  NodejsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda
      Handler: test_handler.test_handler
      Runtime: nodejs8.10
      Events:
        NodejsTest:
          Type: Api
          Properties:
            Path: /nodejs8.10
            Method: get
      Policies:
      - S3ReadPolicy:
          BucketName: riiid.oracle.development
