AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  oracle-api
  http api service for oracle

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        BUCKET_NAME: riiid.oracle.development

Resources:
  FisrtHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: oracle/python-oracle/handler
      Handler: pytest_handler.dev_test_handler
      Runtime: python3.6
      Events:
        PythonTest:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:ap-northeast-1:340519826608:lambda-sep-test 
      Policies:
        - S3ReadPolicy:
            BucketName: riiid.oracle.development